export interface QualifiedEvidenceMigration {
    readonly version: string;
    readonly statements: readonly string[];
}

const immutableFunction = "CREATE OR REPLACE FUNCTION reject_virtual_evidence_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'virtual evidence rows are immutable'; END; $$";

export const QUALIFIED_EVIDENCE_MIGRATIONS: readonly QualifiedEvidenceMigration[] = Object.freeze([
    {
        version: '005_independent_market_marks',
        statements: Object.freeze([
            immutableFunction,
            "CREATE OR REPLACE FUNCTION enforce_virtual_market_mark_fence() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN PERFORM 1 FROM virtual_market_observation_leases WHERE lease_name = NEW.collector_lease_name AND owner_id = NEW.collector_owner_id AND fencing_token = NEW.collector_fence AND expires_at = NEW.collector_expires_at AND expires_at > clock_timestamp() FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'market mark collector lease ownership lost'; END IF; RETURN NEW; END; $$",
            "CREATE TABLE IF NOT EXISTS virtual_market_observation_leases (lease_name TEXT PRIMARY KEY, owner_id TEXT NOT NULL CHECK (btrim(owner_id) <> ''), fencing_token BIGINT NOT NULL CHECK (fencing_token > 0), expires_at TIMESTAMPTZ NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp())",
            "CREATE TABLE IF NOT EXISTS virtual_market_marks (observation_id TEXT PRIMARY KEY, source_identity TEXT NOT NULL UNIQUE, instrument_uid TEXT NOT NULL, broker_observed_at TIMESTAMPTZ NOT NULL, received_at TIMESTAMPTZ NOT NULL, bid_kopecks BIGINT NOT NULL CHECK (bid_kopecks > 0), ask_kopecks BIGINT NOT NULL CHECK (ask_kopecks > 0), mark_kopecks BIGINT NOT NULL CHECK (mark_kopecks > 0), source TEXT NOT NULL CHECK (source = 't-invest-market-data-readonly'), session_status TEXT NOT NULL CHECK (session_status IN ('open', 'closed', 'break')), source_sequence TEXT, payload_fingerprint CHAR(64) NOT NULL CHECK (payload_fingerprint ~ '^[0-9a-f]{64}$'), collector_lease_name TEXT NOT NULL, collector_owner_id TEXT NOT NULL, collector_fence BIGINT NOT NULL CHECK (collector_fence > 0), collector_expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(), CHECK (bid_kopecks <= ask_kopecks), CHECK (mark_kopecks BETWEEN bid_kopecks AND ask_kopecks), CHECK (broker_observed_at <= received_at), UNIQUE (observation_id, instrument_uid), UNIQUE (observation_id, instrument_uid, payload_fingerprint, broker_observed_at), UNIQUE (observation_id, mark_kopecks, broker_observed_at, payload_fingerprint))",
            "DROP TRIGGER IF EXISTS virtual_market_marks_fence ON virtual_market_marks",
            "CREATE TRIGGER virtual_market_marks_fence BEFORE INSERT ON virtual_market_marks FOR EACH ROW EXECUTE FUNCTION enforce_virtual_market_mark_fence()",
            "DROP TRIGGER IF EXISTS virtual_market_marks_commit_fence ON virtual_market_marks",
            "CREATE CONSTRAINT TRIGGER virtual_market_marks_commit_fence AFTER INSERT ON virtual_market_marks DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION enforce_virtual_market_mark_fence()",
            "CREATE INDEX IF NOT EXISTS virtual_market_marks_asof ON virtual_market_marks (instrument_uid, broker_observed_at DESC, observation_id)",
            "DROP TRIGGER IF EXISTS virtual_market_marks_immutable ON virtual_market_marks",
            "CREATE TRIGGER virtual_market_marks_immutable BEFORE UPDATE OR DELETE ON virtual_market_marks FOR EACH ROW EXECUTE FUNCTION reject_virtual_evidence_mutation()"
        ])
    },
    {
        version: '006_qualified_market_mark_sets',
        statements: Object.freeze([
            "ALTER TABLE virtual_observation_experiments ADD COLUMN IF NOT EXISTS config_version SMALLINT, ADD COLUMN IF NOT EXISTS market_data_source TEXT, ADD COLUMN IF NOT EXISTS session_policy_version TEXT, ADD COLUMN IF NOT EXISTS benchmark_instrument_uid TEXT, ADD COLUMN IF NOT EXISTS benchmark_methodology TEXT, ADD COLUMN IF NOT EXISTS benchmark_return_scope TEXT",
            "ALTER TABLE virtual_observation_experiments ADD CONSTRAINT virtual_observation_config_version_shape CHECK ((config_version IS NULL AND market_data_source IS NULL AND session_policy_version IS NULL AND benchmark_instrument_uid IS NULL AND benchmark_methodology IS NULL AND benchmark_return_scope IS NULL) OR (config_version IS NOT DISTINCT FROM 2 AND market_data_source IS NOT DISTINCT FROM 't-invest-market-data-readonly' AND session_policy_version IS NOT DISTINCT FROM 't-invest-session-v1-open-only' AND benchmark_instrument_uid IS NOT NULL AND btrim(benchmark_instrument_uid) <> '' AND benchmark_methodology IS NOT DISTINCT FROM 'normalized-price-return' AND benchmark_return_scope IS NOT DISTINCT FROM 'price-only-excludes-dividends-fees-and-total-return'))",
            "ALTER TABLE virtual_observation_experiments ADD CONSTRAINT virtual_observation_qualified_config_key UNIQUE (experiment_id, benchmark_instrument_uid, session_policy_version)",
            "DROP TRIGGER IF EXISTS virtual_observation_experiments_immutable ON virtual_observation_experiments",
            "CREATE TRIGGER virtual_observation_experiments_immutable BEFORE UPDATE OR DELETE ON virtual_observation_experiments FOR EACH ROW EXECUTE FUNCTION reject_virtual_evidence_mutation()",
            "CREATE TABLE IF NOT EXISTS virtual_market_mark_sets (mark_set_id CHAR(64) PRIMARY KEY CHECK (mark_set_id ~ '^[0-9a-f]{64}$'), experiment_id TEXT NOT NULL, source_tick_id TEXT NOT NULL, valuation_at TIMESTAMPTZ NOT NULL, benchmark_observation_id TEXT NOT NULL, benchmark_instrument_uid TEXT NOT NULL, benchmark_role TEXT NOT NULL DEFAULT 'benchmark' CHECK (benchmark_role = 'benchmark'), session_policy_version TEXT NOT NULL, maximum_age_ms BIGINT NOT NULL CHECK (maximum_age_ms >= 0), maximum_skew_ms BIGINT NOT NULL CHECK (maximum_skew_ms >= 0), created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(), UNIQUE (experiment_id, source_tick_id), UNIQUE (mark_set_id, experiment_id), UNIQUE (mark_set_id, experiment_id, benchmark_observation_id), FOREIGN KEY (experiment_id, benchmark_instrument_uid, session_policy_version) REFERENCES virtual_observation_experiments (experiment_id, benchmark_instrument_uid, session_policy_version))",
            "CREATE TABLE IF NOT EXISTS virtual_market_mark_set_members (mark_set_id CHAR(64) NOT NULL REFERENCES virtual_market_mark_sets(mark_set_id), observation_id TEXT NOT NULL, instrument_uid TEXT NOT NULL, member_role TEXT NOT NULL CHECK (member_role IN ('position', 'benchmark')), payload_fingerprint CHAR(64) NOT NULL CHECK (payload_fingerprint ~ '^[0-9a-f]{64}$'), broker_observed_at TIMESTAMPTZ NOT NULL, PRIMARY KEY (mark_set_id, instrument_uid), UNIQUE (mark_set_id, observation_id), UNIQUE (mark_set_id, observation_id, instrument_uid, member_role), FOREIGN KEY (observation_id, instrument_uid, payload_fingerprint, broker_observed_at) REFERENCES virtual_market_marks(observation_id, instrument_uid, payload_fingerprint, broker_observed_at))",
            "CREATE UNIQUE INDEX IF NOT EXISTS virtual_mark_set_one_benchmark ON virtual_market_mark_set_members(mark_set_id) WHERE member_role = 'benchmark'",
            "ALTER TABLE virtual_market_mark_sets ADD CONSTRAINT virtual_mark_set_benchmark_member_fk FOREIGN KEY (mark_set_id, benchmark_observation_id, benchmark_instrument_uid, benchmark_role) REFERENCES virtual_market_mark_set_members (mark_set_id, observation_id, instrument_uid, member_role) DEFERRABLE INITIALLY DEFERRED",
            "CREATE INDEX IF NOT EXISTS virtual_market_mark_sets_replay ON virtual_market_mark_sets (experiment_id, valuation_at, source_tick_id)",
            "DROP TRIGGER IF EXISTS virtual_market_mark_sets_immutable ON virtual_market_mark_sets",
            "CREATE TRIGGER virtual_market_mark_sets_immutable BEFORE UPDATE OR DELETE ON virtual_market_mark_sets FOR EACH ROW EXECUTE FUNCTION reject_virtual_evidence_mutation()",
            "DROP TRIGGER IF EXISTS virtual_market_mark_set_members_immutable ON virtual_market_mark_set_members",
            "CREATE TRIGGER virtual_market_mark_set_members_immutable BEFORE UPDATE OR DELETE ON virtual_market_mark_set_members FOR EACH ROW EXECUTE FUNCTION reject_virtual_evidence_mutation()"
        ])
    },
    {
        version: '007_normalized_benchmark_evidence',
        statements: Object.freeze([
            "CREATE TABLE IF NOT EXISTS virtual_normalized_benchmark_baselines (experiment_id TEXT PRIMARY KEY REFERENCES virtual_observation_experiments(experiment_id), baseline_mark_set_id CHAR(64) NOT NULL, observation_id TEXT NOT NULL, mark_kopecks BIGINT NOT NULL CHECK (mark_kopecks > 0), broker_observed_at TIMESTAMPTZ NOT NULL, initial_equity_kopecks BIGINT NOT NULL CHECK (initial_equity_kopecks > 0), methodology TEXT NOT NULL CHECK (methodology = 'normalized-price-return'), return_scope TEXT NOT NULL CHECK (return_scope = 'price-only-excludes-dividends-fees-and-total-return'), payload_fingerprint CHAR(64) NOT NULL CHECK (payload_fingerprint ~ '^[0-9a-f]{64}$'), created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(), FOREIGN KEY (baseline_mark_set_id, experiment_id, observation_id) REFERENCES virtual_market_mark_sets (mark_set_id, experiment_id, benchmark_observation_id), FOREIGN KEY (observation_id, mark_kopecks, broker_observed_at, payload_fingerprint) REFERENCES virtual_market_marks (observation_id, mark_kopecks, broker_observed_at, payload_fingerprint))",
            "CREATE TABLE IF NOT EXISTS virtual_normalized_benchmark_points (experiment_id TEXT NOT NULL, scenario_id TEXT NOT NULL, mark_set_id CHAR(64) NOT NULL, valuation_at TIMESTAMPTZ NOT NULL, benchmark_observation_id TEXT NOT NULL, scenario_equity_kopecks BIGINT NOT NULL CHECK (scenario_equity_kopecks >= 0), benchmark_equity_kopecks BIGINT NOT NULL CHECK (benchmark_equity_kopecks >= 0), scenario_pnl_kopecks BIGINT NOT NULL, benchmark_pnl_kopecks BIGINT NOT NULL, scenario_return_bps BIGINT NOT NULL, benchmark_return_bps BIGINT NOT NULL, excess_pnl_kopecks BIGINT NOT NULL, excess_return_bps BIGINT NOT NULL, payload_fingerprint CHAR(64) NOT NULL CHECK (payload_fingerprint ~ '^[0-9a-f]{64}$'), created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(), PRIMARY KEY (experiment_id, scenario_id, mark_set_id), FOREIGN KEY (experiment_id, scenario_id) REFERENCES virtual_shadow_scenario_states(experiment_id, scenario_id), FOREIGN KEY (mark_set_id, experiment_id, benchmark_observation_id) REFERENCES virtual_market_mark_sets (mark_set_id, experiment_id, benchmark_observation_id))",
            "CREATE INDEX IF NOT EXISTS virtual_normalized_benchmark_curve ON virtual_normalized_benchmark_points (experiment_id, scenario_id, valuation_at, mark_set_id)",
            "DROP TRIGGER IF EXISTS virtual_normalized_benchmark_baselines_immutable ON virtual_normalized_benchmark_baselines",
            "CREATE TRIGGER virtual_normalized_benchmark_baselines_immutable BEFORE UPDATE OR DELETE ON virtual_normalized_benchmark_baselines FOR EACH ROW EXECUTE FUNCTION reject_virtual_evidence_mutation()",
            "DROP TRIGGER IF EXISTS virtual_normalized_benchmark_points_immutable ON virtual_normalized_benchmark_points",
            "CREATE TRIGGER virtual_normalized_benchmark_points_immutable BEFORE UPDATE OR DELETE ON virtual_normalized_benchmark_points FOR EACH ROW EXECUTE FUNCTION reject_virtual_evidence_mutation()"
        ])
    }
]);
